config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts, only: [:index, :new, :create]

  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :content, presence: true, length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to root_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:content, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Town Hall</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice.present? %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if alert.present? %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'index', media: 'all', 'data-turbo-track': 'reload' %>

<div class="container">
  <%= image_tag("house.gif", alt: "Description of the image", class: "house") %>  
  <h1>Town Hall</h1>
  <div>
    <%= link_to "Log in", new_user_session_path, method: :get unless user_signed_in? %>
    <%=" to reveal the speaker" unless user_signed_in? %>
  </div>

  <div class="scrollable-posts">
    <% @posts.each do |post| %>
      <div class="post">
        <div class="username"><%= "#{post.user.username}:" if user_signed_in? %></div>
        <em>
          <div class="post-content"><%= post.content %></div>
        </em>
      </div>
    <% end %>
  </div>

  <div>
    <%= link_to "New Post", new_post_path, class: 'btn-3d' %>
  </div>
  
  <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'btn-3d-grey' if user_signed_in? %>
</div>

app/views/posts/new.html.erb
<%= stylesheet_link_tag 'new_post', media: 'all', 'data-turbo-track': 'reload' %>

<div class="container">
  <%= image_tag("house.gif", alt: "Description of the image", class: "house") %>  
  <h1>
    <a href="<%= root_path %>">Town Hall</a>
  </h1>
  <%= form_with model: @post do |form| %>
    <div class="form">
      <div class="label">
        <div><%= form.label :content, "New Post: " %></div>
      </div>
      <div class="text-field">
        <div><%= form.text_field :content %></div>
      </div>
      <div class="submit">
        <div><%= form.submit "Submit!" %></div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/shared/_error_messages.html.erb
<%= stylesheet_link_tag 'authentication', media: 'all', 'data-turbo-track': 'reload' %>

<div class="container">
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= I18n.t("errors.messages.not_saved",
                   count: resource.errors.count,
                   resource: resource.class.model_name.human.downcase)
         %>
      </h2>
      <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/users/shared/_links.html.erb
<%= stylesheet_link_tag 'authentication', media: 'all', 'data-turbo-track': 'reload' %>

<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>